name: BobTheBuilder

on: [push]

jobs:
  build:

    runs-on: [self-hosted, linux]
    
    steps:
    #- uses: actions/checkout@v2
             
    - name: Build the Project (Initial Compile)
      run: ls && cd .. && ls
        #rm -r build &&
        #mkdir build &&
        #cd build &&
        #cmake .. &&
        #make -j4
        
    - name: Create .deb file
      run: echo test
        #cd ../.. &&
        #tar -zcvf libwallaby.tar.gz libwallaby &&
        #cp libwallaby.tar.gz libwallaby &&
        #cd libwallaby &&
        #dpkg-buildpackage -b -rfakeroot -us -uc
        
    - name: Upload .deb to KIPR-Update
      run:
        echo Not yet implemented.
        #This code should upload but test it first.
        #git clone https://github.com/kipr/KIPR-Update
        #cp *.deb KIPR-Update
        #cd KIPR-Update
        #git add *.deb
        #git commit -m "Automated Commit: Libwallaby"
        #git push origin master
