

name: BobTheBuilder

#BobTheBuilder
#Author: Zachary Sasser (KISS Institute for Practical Robotics)
#
#This program builds the debian files upon push to master.

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - master         # Push events on master branch
      - Zacharyprime-WorkflowTesting #Push events on my testing branch

jobs:
  build:

    runs-on: [self-hosted, linux]
    
    steps:
    #- uses: actions/checkout@v2 (BROKEN?)
           
    #I know that the actions/checkout@v2 function is SUPPOSED to do this... Doesn't work on the Wombat.
    - name: Get libwallaby from github
      run: 
        #Make sure we are in a clean enviroment
        sudo rm -r /home/pi/got2 && 
        mkdir /home/pi/got2 &&
        #Get the repository
        cd /home/pi/got2 &&
        git clone https://github.com/kipr/libwallaby 
        
    #Setup the enviroment for the package to be created.
    - name: Setup Enviroment
      run: 
        cd /home/pi/got2 &&
        tar -zcvf libwallaby.tar.gz libwallaby &&
        cp libwallaby.tar.gz libwallaby &&
        
    #Builds everything into a .deb file using dpkg-buildpackage
    - name: Create .deb file
      run: echo test
        cd /home/pi/got2/libwallaby &&
        dpkg-buildpackage -b -rfakeroot -us -uc
        
    - name: Upload .deb to KIPR-Update
      run:
        echo Not yet implemented.
        #This code should upload but test it first.
        #git clone https://github.com/kipr/KIPR-Update
        #cp *.deb KIPR-Update
        #cd KIPR-Update
        #git add *.deb
        #git commit -m "Automated Commit: libwallaby"
        #git push origin master
